name: Pull request
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: aslafy-z/conventional-pr-title-action@master
        with:
          preset: conventional-changelog-angular@^5.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
