name: Pull request
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: aslafy-z/conventional-pr-title@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
